version: '3.1'

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - front-network
      - back-network
    environment:
      - TZ=Asia/Seoul
  certbot:
    container_name: certbot
    image: certbot/certbot:arm64v8-nightly
    restart: unless-stopped
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - PASSWORD= #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD= #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./docker/Config/code-server/config:/config
    ports:
      - PORT:PORT
    restart: unless-stopped
