version: '3.1'

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - front-network
      - back-network
    environment:
      - TZ=Asia/Seoul
  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot:arm64v8-nightly
  #   restart: unless-stopped
